paths:
  /pet:
    PUT:
      name: 更新现有宠物信息
      body:
        - name: 更新商店中已存在的宠物
          is_have: 必需
          format: string
          dome: sadesex
          remark: 这是其中的一个字段
        - name: sexex
          is_have: 必需
          format: array
          dome:
            - a: sae
            - a: sec
          remark: sesaer
      responseData:
        - name: sade
          is_have: 必需
          format: string
          http_dome: 这是一个接口
          remark: ""
          node: []
    POST:
      name: 将新宠物添加到商店
      body:
        - name: swe
          is_have: 非必需
          format: integer
          dome: 12
          remark: ""
        - name: sevxee
          is_have: 必需
          format: number
          dome: 12.12
          remark: 实例数据
      responseData:
        - name: sadesc
          is_have: 必需
          format: string
          http_dome: 色彩位数
          remark: ""
          node: []
        - name: sadesc
          is_have: 必需
          format: string
          http_dome: 色彩位数
          remark: ""
          node: []
  /pet/findByStatus:
    GET:
      name: 根据状态查找宠物
      query:
        - name: status
          is_have: 必需
          format: string
          dome: sderd
          remark: ""
      responseData:
        - name: sexe
          is_have: 非必需
          format: object
          dome:
            a: sdae
            b: sexc
          http_dome: 人们的的
          remark: ""
          node:
            - name: secxr
              is_have: 非必需
              format: string
              dome: sdedxe
              http_dome: 上的广告
              remark: ""
              node: []

  /pet/findByTags:
    GET:
      name: Finds Pets by tags
      query:
        - name: tags
          is_have: true
          format: string
          dome: 这是一个示范样例
          remark: ""
      responseData:
        - name: asdd
          is_have: 必需
          format: string
          http_dome: 上的重新发
          remark: ""
          node: []

  /pet/{petId}:
    GET:
      name: Find pet by ID
      query:
        - name: petId
          is_have: 必需
          format: object
          dome:
            a: sdasd
            b: sdedxxc
          remark: ""
      responseData:
        - name: sdec
          is_have: 必需
          format: array
          http_dome: 是的哇
          remark: ""
          node:
            - name: scece
              is_have: 必需
              format: string
              http_dome: 手册
              remark: ""
              node: []
            - name: xievvr
              is_have: 非必需
              format: string
              http_dome: 删除了人们
              remark: ""
              node: []

    POST:
      name: Updates a pet in the store with form data
      query:
        - name: petId
          is_have: 必需
          format: integer
          dome: 14
          remark: ""
        - name: petId
          is_have: 必需
          format: string
          dome: 我能输出呢
          remark: ""
      responseData:
        - name: scervv
          is_have: sexr
          format: string
          http_dome: 手册地方
          remark: ""
          node: []
    DELETE:
      name: Deletes a pet
      query:
        - name: api_key
          is_have: 必需
          format: string
          dome: scece
          remark: ""
      responseData:
        - name: rkbkuti
          is_have: 非必需
          format: number
          http_dome: 首次承认
          remark: ""
          node: []
