info:
  title: ApiPlayer
  description: 第六届青训营前端大项目2 - HTTP 接口管理平台
  version: 1.0.0
tags:
  - name: 项目详情
paths:
  /apis/apiinfo:
    get:
      summary: 获取某API详情信息
      x-apifox-folder: 项目详情
      x-apifox-status: developing
      deprecated: false
      description: 点击左侧栏某个API后，在右侧主界面获取到该API的详细信息并加以展示。
      tags:
        - 项目详情
      parameters:
        - name: api_id
          in: query
          description: 接口的id
          required: false
          type: number
          x-example: ''
        - name: Authorization
          in: header
          description: ''
          type: string
          x-example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJ1c2VybmFtZSI6Im5vbl9oYW5hIiwiZW1haWwiOiJ6aG91eGlhbmc3NTdAZ21haWwuY29tIiwiaW50cm9kdWNlIjoi6buY6K6k5LuL57uNIiwiYXZhdGFyIjoiaHR0cDovLzEzLjExNS4xMTkuMTM5OjMwMDAvdXBsb2Fkcy9pbWFnZXMvYXZhdGFycy8xNjkyNzU4Mjc1NzgwXzczOTYwNTAwMi5qcGVnIiwiaWF0IjoxNjkzMDk4MDg0LCJleHAiOjE2OTMxODQ0ODR9.7R6SNwbiMxo62G8ADolyfPFuT3ej7cHV7Rj_0blcwog
      responses:
        '200':
          description: 成功
          schema:
            type: object
            properties:
              result_code:
                type: number
                title: 状态码
                description: 0-成功，1-失败
                additionalProperties: false
              result_msg:
                type: string
                title: 状态信息
                additionalProperties: false
              api_info:
                type: object
                properties:
                  api_id:
                    type: number
                    title: 接口id
                    additionalProperties: false
                  dictionary_id:
                    type: number
                    title: 接口所属的目录id
                  api_editor_id:
                    type: number
                    title: 最近一次修改这个api的人的id
                  api_creator_id:
                    type: number
                    title: 接口创建人的id
                  api_createdAt:
                    type: string
                    title: 接口创建时间
                    description: 'yyyy-MM-dd hh:mm:ss的形式。'
                  api_editedAt:
                    type: string
                    title: 接口修改时间
                    description: 'yyyy-MM-dd hh:mm:ss的形式。'
                  api_name:
                    type: string
                    title: 接口名称
                    additionalProperties: false
                  api_method:
                    type: string
                    title: 接口请求方法
                    description: 以一般的字符串进行填写，比如GET方法就直接写'GET'。
                  api_url:
                    type: string
                    title: 接口请求url地址
                    additionalProperties: false
                  api_status:
                    type: number
                    title: 接口状态
                    description: 0-开发中，1-测试中，2-已发布，3-将废弃
                    additionalProperties: false
                  api_principal_id:
                    type: number
                    title: 该接口的负责人id
                    additionalProperties: false
                  api_desc:
                    type: string
                    title: 接口说明
                    additionalProperties: false
                  baseUrl:
                    type: string
                    title: 该接口的前置url
                  api_request_params:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: number
                          title: 请求参数的顶层类型
                          description: >-
                            0-Params，1-Body(form-data)，2-Body(x-www-form-unlencoded)，3-Cookie，4-Header。此处以Params参数为例，也就是表格的形式来填写参数。
                          additionalProperties: false
                        params_list:
                          type: array
                          items:
                            type: object
                            properties:
                              param_name:
                                type: string
                                title: 参数名称
                                additionalProperties: false
                              param_type:
                                type: integer
                                title: 参数类型
                                description: 0-number，1-integer，2-string，3-array
                              param_desc:
                                type: string
                                title: 参数说明
                                additionalProperties: false
                            x-apifox-orders:
                              - param_name
                              - param_type
                              - param_desc
                            required:
                              - param_name
                              - param_type
                              - param_desc
                            x-apifox-ignore-properties: []
                          title: 参数列表
                      x-apifox-orders:
                        - type
                        - params_list
                      required:
                        - type
                      x-apifox-ignore-properties: []
                    title: 接口的请求参数
                  api_request_JSON:
                    type: string
                    title: 接口的请求体
                    description: Body-JSON
                  api_responses:
                    type: array
                    items:
                      type: object
                      properties:
                        response_id:
                          type: integer
                          title: 响应的id
                        http_status:
                          type: string
                          title: 返回时的HTTP状态码
                        response_name:
                          type: string
                          title: 返回响应的名称
                        response_body:
                          type: string
                          title: 返回响应主体
                          description: 规定以JSON形式的数据进行返回。跟在TypeScript中规定某interface的形式类似。
                      x-apifox-orders:
                        - response_id
                        - http_status
                        - response_name
                        - response_body
                      required:
                        - http_status
                        - response_body
                        - response_name
                        - response_id
                      x-apifox-ignore-properties: []
                    title: 接口返回响应
                x-apifox-orders:
                  - api_id
                  - dictionary_id
                  - api_editor_id
                  - api_creator_id
                  - api_createdAt
                  - api_editedAt
                  - api_name
                  - api_method
                  - api_url
                  - api_status
                  - api_principal_id
                  - api_desc
                  - baseUrl
                  - api_request_params
                  - api_request_JSON
                  - api_responses
                required:
                  - api_id
                  - api_name
                  - api_url
                  - api_status
                  - api_principal_id
                  - baseUrl
                  - api_desc
                  - api_request_params
                  - api_method
                  - dictionary_id
                  - api_editor_id
                  - api_creator_id
                  - api_createdAt
                  - api_editedAt
                  - api_request_JSON
                  - api_responses
                x-apifox-ignore-properties: []
            x-apifox-orders:
              - result_code
              - result_msg
              - api_info
            required:
              - result_code
              - result_msg
              - api_info
            x-apifox-ignore-properties: []
      x-run-in-apifox: 'https://apifox.com/web/project/3099285/apis/api-101341797-run'
      produces:
        - application/json
swagger: '2.0'
host: '13.115.119.139:3000'
schemes:
  - http
basePath: /
definitions: {}
x-components: {}
